### ISSUE TITLE
How do i create a program?

### ISSUE THREAD

**Issue by MrPigeontheCoder** [hasha2982/Py93#9]
I do not know how to create a program... I would like to know how to do so... By program i mean a .py (and other python extensions) file

**Comment by hashadex** [comment]
Oh hi, @MrPigeontheCoder, sorry for not answering for a long time, only noticed now.

You can create a file with a .py extension anywhere you like and launch Py93 compiler in the shell.

```
py93 c /a/foo.py
```

This will compile your file (which is located in /a/) and put it in /a/Py93/compiled/ as an HTML file.

You can change the output directiory with the --out flag

You can get more info with `py93 c help`

Keep in mind that the project is not maintained anymore, but i'll be happy to answer some questions

**Comment by MrPigeontheCoder** [comment]
thanks
